baseURL: https://code-explorer.github.io

languageCode: en-us
title: "Satwik Kambham"
theme: "toha"

# Manage languages
# The official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth for blog
# markup:
#   tableOfContents:
#     startLevel: 2
#     endLevel: 6
#     ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/code-explorer/code-explorer.github.io

  # Specify whether blog posts should be enabled or not
  enableBlogPost: false

  # specify whether Table of Contents should be shown in reading page
  enableTOC: false

  # Background image of the website
  background: "images/Background.jpg"

  # Logo of website
  logo:
      main: "images/logo inverted.png"
      inverted: "images/logo.png"
      favicon: images/favicon.png

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
